name: secrets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Echo secret
        run: echo "Hello, world! This is my secret |${{ secrets.MY_SECRET }}|"

      - name: Echo secret through file
        run: |
          echo "Hello, world! This is my secret |${{ secrets.MY_SECRET }}|" > secret.txt
          echo cat secret.txt
          cat secret.txt
          echo "-->THIS SHOULD BE HIDDEN<--"
